### ISSUE TITLE
Force Ansible scripts to use Python3

### ISSUE THREAD

**Issue by justb4** [Geonovum/ogc-api-testbed#45]
This came up when using this repo as Template for a [EC-JRC instance](https://github.com/justb4/ogc-api-jrc) at https://jrc.map5.nl. The VM uses Ubuntu 21.04. The Python defaults did not work. Calling `python` was using Python 2, which is still the default. To force Python3 we adapted the Inventory config file, here [prod.yml](https://github.com/Geonovum/ogc-api-testbed/blob/main/ansible/hosts/prod.yml) to read:

```
ogcapijrc:
  hosts:
    OGCAPIJRC:
       ansible_port: ...
       ansible_host: jrc.map5.nl
       ansible_user: ...
       ansible_python_interpreter: /usr/bin/python3
```
Line added is `ansible_python_interpreter: /usr/bin/python3`.
